# Generated by Django 4.0.6 on 2022-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_profile_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
