# Generated by Django 4.0.6 on 2022-08-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
