# Generated by Django 4.0.6 on 2022-08-01 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
