# Generated by Django 4.0.6 on 2022-08-01 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile2',
        ),
    ]
