# Generated by Django 4.0.6 on 2022-08-01 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
