# Generated by Django 3.2.14 on 2022-08-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_delete_comment'),
        ('backend', '0013_delete_profile2'),
        ('backend', '0013_profile_alter_comment_user'),
        ('backend', '0014_profile_alter_comment_user'),
        ('backend', '0015_profile'),
        ('backend', '0016_profile'),
    ]

    operations = [
    ]
